analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - control_statement
  - empty_count
  - empty_string
  - trailing_newline
  - colon
  - comma
  - unused_closure_parameter
  - unused_control_flow_label
  - no_space_in_method_call
  - void_return
  - syntactic_sugar
  - discarded_notification_center_observer
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - closure_spacing
  - discouraged_direct_init
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - for_where
  - implicit_getter
  - is_disjoint
  - leading_whitespace
  - trailing_semicolon
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - mark
  - multiple_closures_with_trailing_closure
  - notification_center_detachment
  - overridden_super_call
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - redundant_nil_coalescing
  - return_arrow_whitespace
  - statement_position
  - superfluous_disable_command
  - unneeded_break_in_switch
  - unused_enumerated
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_whitespace
  - weak_delegate
  - nimble_operator
  - operator_usage_whitespace
  - vertical_parameter_alignment
  - comment_spacing
